name: wewantfans
favicon: null
layout_spectrum: 0.9322
typography_spectrum: 0.74787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d4cf'
    - '#2e3b6c'
    - '#abaeaa'
    - '#1c1d0b'
    - '#545e60'
  brandStrength: 0.5512994793243706
  lightness: 0.8943433300592005
  saturation: 0.2985235338564962
  rhythmicContrast: 0.15922312438488007
purpose: []
