favicon: null
name: wewantfans
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2985235
  brandStrength: 0.5512994793243706
  lightness: 0.5303541
  brandColors:
    - '#d3d4cf'
    - '#2e3b6c'
    - '#abaeaa'
    - '#1c1d0b'
    - '#545e60'
  rhythmicContrast: 0.4721754
typography_spectrum: 0.5261383
layout_spectrum: 0.5092749
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
